In [4]:
import numpy as np

In [5]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [6]:
# Get a specific element [r, c]
a[1, 5]

13

In [8]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
# Get a specific column
a[:, 2]


array([ 3, 10])

In [10]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]


array([2, 4, 6])

In [11]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [12]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
# Get specific element (work outside in)
b[0,1,1]

4

In [16]:
# replace 
b[:,1,:] = [[9,9],[8,8]]

In [17]:
b


array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])