In [2]:
import numpy as np

In [3]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [7]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [8]:
# Any other number (full_like)
np.full_like(a, 4)

NameError: name 'a' is not defined

In [9]:
# Random decimal numbers
np.random.rand(4,2)


array([[0.33761639, 0.51182224],
       [0.2314213 , 0.91540197],
       [0.79339498, 0.69025061],
       [0.76088647, 0.71462413]])

In [10]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 1, -2, -2],
       [ 0,  3,  0],
       [ 4,  4,  3]])

In [11]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)


[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [13]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]
