In [11]:
import numpy as np

In [21]:
x = np.array([1,2,3])
y = np.array([5,6,7])
print (x*y)

[ 5 12 21]


In [22]:
x1 = np.array([1,2,3])
y1 = np.array([5,6,7])
print(x1+y1)

[ 6  8 10]


In [26]:
#2d array
a2 = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(a2)

[[9. 8. 7.]
 [6. 5. 4.]]


In [30]:
#3d
b3 = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0],[99.0,11.2,55.6]])
print(b3)

[[ 9.   8.   7. ]
 [ 6.   5.   4. ]
 [99.  11.2 55.6]]


In [28]:
# Get Dimension
a2.ndim


2

In [32]:
x.ndim

1

In [33]:
# Get Shape
a2.shape


(2, 3)

In [34]:
# Get Shape
b3.shape


(3, 3)

In [35]:
# Get Type
a2.dtype


dtype('float64')

In [36]:
# Get Type
b3.dtype

dtype('float64')

In [46]:
#dinifning sepecific size
s = np.array([1,2,3], dtype='int32')
print(s)

[1 2 3]


In [38]:
s.dtype

dtype('int16')

In [55]:
# Get Size
s.size


3

In [56]:
# Get itemsize - int size
s.itemsize

4

In [57]:
#Get size
b3.size

9

In [53]:
#Get itemsize
b3.itemsize

8

In [50]:
# Get total size
b3.size * b3.itemsize

72

In [51]:
# Get total size
b3.nbytes

72

In [58]:
# Get number of elements
b3.size

9